### ISSUE TITLE
Management API Authentication settings not working

### ISSUE THREAD

**Issue by ykosaka-welyco** [prismagraphql/prisma-templates#7]
# What I faced

I set managementApiSecret, however I got the error below.

```
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
```

And I tried to deploy prisma service without secret key, and deployment succeeded.

# Possible Causes

The management api secret is loaded from `PRISMA_MANAGEMENT_API_JWT_SECRET `.

https://github.com/prismagraphql/prisma/blob/b58e9f7c8bd58619f7df343dfea83590f5216ca3/server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala#L67

but cloud formation template sets secret key as `MANAGEMENT_API_SECRET `. 

https://github.com/prismagraphql/prisma-templates/blob/master/aws/fargate.yml#L274

**Comment by dpetrick** [comment]
Thanks, fixed in 851438eea4171a0ef40de887e999318e2e9e03a7.

**Comment by ykosaka-welyco** [comment]
Thank you very much.

**Comment by patrick-samy** [comment]
I'm experiencing the same behavior after setting `managementApiSecret` in my config map for my Kubernetes pod, using the image: `prismagraphql/prisma:1.13`

Any ideas?

**Comment by bag-man** [comment]
@patrick-samy Same issue! Has it changed to a JWT or something?

**Comment by bag-man** [comment]
@patrick-samy Same issue. Did you find a fix?
